version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports: 
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/var/www/laravel
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./laravel
      target: dev
    volumes: 
      - ./laravel:/var/www/laravel
    depends_on: 
      - db

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootPass
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
    volumes:
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - db-data:/var/lib/mysql

volumes:
  db-data:
